# This is a basic workflow to help you get started with Actions

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x # Or your target .NET version

                # **Add a NuGet package restore step**
      - name: Restore NuGet packages
        run: dotnet restore src/Resume-Blazor.csproj # Specify the path to your project file


      # Your step to replace Firebase Config Placeholders
      - name: Replace Firebase Config Placeholders
        run: |
          sed -i 's|ApiKey|${{ secrets.ApiKey }}|g' src/wwwroot/appsettings.json
          sed -i 's|AuthDomain|${{ secrets.AuthDomain }}|g' src/wwwroot/appsettings.json
          sed -i 's|ProjectId|${{ secrets.ProjectId }}|g' src/wwwroot/appsettings.json
          sed -i 's|StorageBucket|${{ secrets.StorageBucket }}|g' src/wwwroot/appsettings.json
          sed -i 's|MessagingSenderId|${{ secrets.MessagingSenderId }}|g' src/wwwroot/appsettings.json
          sed -i 's|AppId|${{ secrets.AppId }}|g' src/wwwroot/appsettings.json
          sed -i 's|MeasurementId|${{ secrets.MeasurementId }}|g' src/wwwroot/appsettings.json
        shell: bash

  # Your .NET Publish step
      - name: .NET Publish
        run: dotnet publish src/Resume-Blazor.csproj -c Release -o release --no-restore

      # Add other steps as needed (e.g., deployment)

       # **Add the GitHub Pages deployment step**
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./publish_output/wwwroot # **Deploy the contents of the wwwroot within the publish output**
          publish_branch: gh-pages
          # cname: your-custom-domain.com