- name: Replace Firebase Config Placeholders
        run: |
          sed -i 's|__FIREBASE_API_KEY__|${{ secrets.FIREBASE_API_KEY }}|g' src/wwwroot/appsettings.json
          sed -i 's|__FIREBASE_AUTH_DOMAIN__|${{ secrets.FIREBASE_AUTH_DOMAIN }}|g' src/wwwroot/appsettings.json
          sed -i 's|__FIREBASE_PROJECT_ID__|${{ secrets.FIREBASE_PROJECT_ID }}|g' src/wwwroot/appsettings.json
          sed -i 's|__FIREBASE_STORAGE_BUCKET__|${{ secrets.FIREBASE_STORAGE_BUCKET }}|g' src/wwwroot/appsettings.json
          sed -i 's|__FIREBASE_MESSAGING_SENDER_ID__|${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}|g' src/wwwroot/appsettings.json
          sed -i 's|__FIREBASE_APP_ID__|${{ secrets.FIREBASE_APP_ID }}|g' src/wwwroot/appsettings.json
          sed -i 's|__FIREBASE_MEASUREMENT_ID__|${{ secrets.FIREBASE_MEASUREMENT_ID }}|g' src/wwwroot/appsettings.json
        shell: bash # Specify the shell for the sed command

      # Add your dotnet build or publish step after this replacement step
      - name: .NET Publish
        run: dotnet publish src/Resume-Blazor.csproj -c Release -o release --no-restore
