 name: Replace Firebase Config Placeholders
  run: |
    sed -i 's|ApiKey|${{ secrets.ApiKey }}|g' src/wwwroot/appsettings.json
    sed -i 's|AuthDomain|${{ secrets.AuthDomain }}|g' src/wwwroot/appsettings.json
    sed -i 's|ProjectId|${{ secrets.ProjectId }}|g' src/wwwroot/appsettings.json
    sed -i 's|StorageBucket|${{ secrets.StorageBucket }}|g' src/wwwroot/appsettings.json
    sed -i 's|MessagingSenderId|${{ secrets.MessagingSenderId }}|g' src/wwwroot/appsettings.json
    sed -i 's|AppId|${{ secrets.AppId }}|g' src/wwwroot/appsettings.json
    sed -i 's|MeasurementId|${{ secrets.MeasurementId }}|g' src/wwwroot/appsettings.json
  shell: bash

# Add your dotnet build or publish step after this replacement step
 name: .NET Publish
  run: dotnet publish src/Resume-Blazor.csproj -c Release -o release --no-restore
